name: Create GitHub Release

#on:
#  push:
#    tags:
#      - 'v*' # Create releases when tags starting with 'v' are pushed
#
#jobs:
#  create_release:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.17 # You can change this to your desired Go version
#
#      - name: Install GitHub Release Action
#        uses: softprops/action-gh-release@v1
#        with:
#          files: |
#            # List the files you want to include in the release
#            ./path/to/file1
#            ./path/to/file2
#          token: ${{ secrets.RELEASE_TOKEN }}
#
#      - name: Create Git Tag
#        run: git tag -a ${{ github.ref }} -m "Release ${{ github.ref }}"
#        if: startsWith(github.ref, 'refs/tags/v')
#
#      - name: Push Git Tag
#        run: git push origin ${{ github.ref }}
#        if: startsWith(github.ref, 'refs/tags/v')
#

on:
    workflow_dispatch: # This event allows you to manually trigger the workflow

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
          - name: display hello world
            run: echo "Hello World"
          - name: Checkout code
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - name: 'Get Previous tag'
            id: previoustag
            uses: "WyriHaximus/github-action-get-previous-tag@v1"
            with:
              fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
          - name: check tags
            run: git describe --tags --abbrev=0
          - name: display file 1
            run: cat file.txt
          - name: Read Release Version
            id: get_version
            run: |
              # Read the release version from a text file
              echo "::set-output name=version::${{ steps.latesttag.outputs.tag }}"
            shell: bash
          - name: display version
            run: echo ${{ steps.get_version.outputs.version }}
          - name: display token
            run: echo ${{ secrets.REPO_TOKEN }}
          - name: create release
            uses: softprops/action-gh-release@v1
            with:
              files: |
                ./file.txt
              tag_name: ${{ steps.get_version.outputs.version }}
              token: ${{ secrets.REPO_TOKEN }}