name: Create GitHub Release

#on:
#  push:
#    tags:
#      - 'v*' # Create releases when tags starting with 'v' are pushed
#
#jobs:
#  create_release:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.17 # You can change this to your desired Go version
#
#      - name: Install GitHub Release Action
#        uses: softprops/action-gh-release@v1
#        with:
#          files: |
#            # List the files you want to include in the release
#            ./path/to/file1
#            ./path/to/file2
#          token: ${{ secrets.RELEASE_TOKEN }}
#
#      - name: Create Git Tag
#        run: git tag -a ${{ github.ref }} -m "Release ${{ github.ref }}"
#        if: startsWith(github.ref, 'refs/tags/v')
#
#      - name: Push Git Tag
#        run: git push origin ${{ github.ref }}
#        if: startsWith(github.ref, 'refs/tags/v')
#

on:
    workflow_dispatch: # This event allows you to manually trigger the workflow

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
          - name: display hello world
            run: echo "Hello World"
          - name: Checkout code
            uses: actions/checkout@v3
          - name: ls
            run: ls
          - name: display file 1
            run: cat file.txt
          - name: create release
            uses: softprops/action-gh-release@v1
            with:
              files: |
                # List the files you want to include in the release
                ./file.txt
              token: ${{ secrets.REPO_TOKEN }}